routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductVariantController;
use App\Http\Controllers\SizeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** Tài khoản đăng nhập
 *  Email: ductiep1610@gmail.com
 *  Password: 16101996
 */
Route::get('/cms', [AuthController::class, 'login'])->name('login');
Route::post('/cms', [AuthController::class, 'postlogin'])->name('post.login-admin');
Route::get('/logout', [AuthController::class, 'logout'])->name('post.logout-admin');
Route::group(['prefix' => 'admins', 'middleware' => ['auth:admin']], function () {
    Route::get('/', [AdminController::class, 'index'])->name('admin.dashboard');

    Route::group(['prefix' => 'categories'], function () {
        Route::get('/', [CategoryController::class, 'index'])->name('category.index');
        Route::get('/add', [CategoryController::class, 'create'])->name('category.create');
        Route::post('/add', [CategoryController::class, 'store'])->name('category.store');
        Route::get('/edit/{cate_slug}', [CategoryController::class, 'edit'])->name('category.edit');
        Route::post('/update/{id}', [CategoryController::class, 'update'])->name('category.update');
        Route::get('/delete/{id}', [CategoryController::class, 'destroy'])->name('category.destroy');
        Route::get('/change/{id}', [CategoryController::class, 'changeStatus'])->name('category.change.status');
    });

    Route::group(['prefix' => 'accounts'], function () {
        Route::get('/', [AccountController::class, 'index'])->name('accounts.index');
        Route::post('/add', [AccountController::class, 'store'])->name('accounts.store');
        Route::get('/edit/{id}', [AccountController::class, 'edit'])->name('accounts.edit');
        Route::post('/update', [AccountController::class, 'update'])->name('accounts.update');
        Route::get('/delete/{id}', [AccountController::class, 'destroy'])->name('accounts.destroy');
        Route::get('/change/{id}', [AccountController::class, 'changeStatus'])->name('accounts.change.status');
    });

    Route::group(['prefix' => 'coupons'], function () {
        Route::get('/', [CouponController::class, 'index'])->name('coupons.index');
        Route::get('/add', [CouponController::class, 'create'])->name('coupons.create');
        Route::post('/add', [CouponController::class, 'store'])->name('coupons.store');
        Route::get('/edit/{id}', [CouponController::class, 'edit'])->name('coupons.edit');
        Route::post('/update/{id}', [CouponController::class, 'update'])->name('coupons.update');
        Route::get('/delete/{id}', [CouponController::class, 'destroy'])->name('coupons.destroy');
        Route::get('/change/{id}', [CouponController::class, 'changeStatus'])->name('coupons.change.status');
    });

    Route::group(['prefix' => 'sizes'], function () {
        Route::get('/', [SizeController::class, 'index'])->name('sizes.index');
        Route::post('/add', [SizeController::class, 'store'])->name('sizes.store');
        Route::get('/edit/{id}', [SizeController::class, 'edit'])->name('sizes.edit');
        Route::post('/update', [SizeController::class, 'update'])->name('sizes.update');
        Route::get('/delete/{id}', [SizeController::class, 'destroy'])->name('sizes.destroy');
    });

    Route::group(['prefix' => 'colors'], function () {
        Route::get('/', [ColorController::class, 'index'])->name('colors.index');
        Route::post('/add', [ColorController::class, 'store'])->name('colors.store');
        Route::get('/edit/{id}', [ColorController::class, 'edit'])->name('colors.edit');
        Route::post('/update', [ColorController::class, 'update'])->name('colors.update');
        Route::get('/delete/{id}', [ColorController::class, 'destroy'])->name('colors.destroy');
    });

    Route::group(['prefix' => 'products'], function () {
        Route::get('/not-approved', [ProductController::class, 'index'])->name('products.index');
        Route::get('/approved', [ProductController::class, 'listApproved'])->name('products.listApproved');
        Route::get('/add', [ProductController::class, 'create'])->name('products.create');
        Route::post('/add', [ProductController::class, 'store'])->name('products.store');
        Route::get('/show/{id}', [ProductController::class, 'show'])->name('products.show');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('products.edit');
        Route::post('/update/{id}', [ProductController::class, 'update'])->name('products.update');
        Route::get('/delete/not-approved/{id}', [ProductController::class, 'destroy'])->name('products.destroy');
        Route::get('/delete/approved/{id}', [ProductController::class, 'getDeleteApproved'])->name('products.getDeleteApproved');
        Route::get('/delete/{id}/{id_image}', [ProductController::class, 'getdeleteImageDetail'])->name('products.getdelImageDetail');
        Route::get('/change/{id}', [ProductController::class, 'changeStatus'])->name('products.change.status');
        Route::get('/browse-product/{id}', [ProductController::class, 'getbrowseProduct'])->name('products.getbrowseProduct');
    });

    Route::group(['prefix' => 'product/variants'], function () {
        Route::get('/{product_id}', [ProductVariantController::class, 'index'])->name('variants.index');
        Route::post('/add', [ProductVariantController::class, 'store'])->name('variants.store');
        Route::get('/{product_id}/edit/{id}', [ProductVariantController::class, 'edit'])->name('variants.edit');
        Route::post('{product_id}/update/{id}', [ProductVariantController::class, 'update'])->name('variants.update');
        Route::get('{product_id}/delete/{id}', [ProductVariantController::class, 'destroy'])->name('variants.destroy');
    });
});

Route::get('/', [PagesController::class, 'index'])->name('home.index');
Route::get('/blog', [PagesController::class, 'getBlogPage'])->name('blog.index');
Route::get('/blog/name', [PagesController::class, 'getBlogDetailPage'])->name('blog_detail.index');
Route::get('/contact', [PagesController::class, 'getContactPage'])->name('contact.index');
Route::get('/product', [PagesController::class, 'getProductPage'])->name('product.index');
Route::get('/shop', [PagesController::class, 'getShopPage'])->name('shop.index');
Route::get('/login', [PagesController::class, 'getLoginPage'])->name('login.index');
Route::get('/register', [PagesController::class, 'getRegisterPage'])->name('register.index');
Route::get('/shopping-cart', [CartController::class, 'index'])->name('cart.index');
Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout.index');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    const STATUS_DEFAULT = 2;
    const STATUS_ACTIVE = 1;
    const STATUS_HIDEN = 0;

    protected $fillable = [
        'product_name',
        'cate_id',
        'price',
        'promotion',
        'description',
        'image',
        'slug',
        'qty',
        'focus',
        'status',
        'amount_sold',
        'admin_id',
    ];

    public function admin()
    {
        return $this->belongsTo(Admin::class, 'admin_id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'cate_id');
    }

    public function images()
    {
        return $this->hasMany(ImageProduct::class,'product_id');
    }

    public function productVariants()
    {
        return $this->hasMany(ProductVariant::class,'product_id');
    }

    public function getImageUrlAttribute()
    {
        return $this->image ? asset('uploads/products/' . $this->image) : '';
    }

    public function getFormatPriceAttribute()
    {
        return number_format($this->price, 0, ',','.');
    }

    public function getFormatPromotionAttribute()
    {
        return number_format($this->price*(100 - $this->promotion)/100, 0, ',','.');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AddProductRequest;
use App\Models\Admin;
use App\Models\ImageProduct;
use App\Repositories\Eloquents\Category\CategoryRepositoriesInterface;
use App\Traits\UploadsImageTraits;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Symfony\Component\HttpFoundation\Response;

class ProductController extends Controller
{
    use UploadsImageTraits;

    private $product;
    private $cateRepo;
    private $imageProduct;

    public function __construct(CategoryRepositoriesInterface $cateRepo, Product $product, ImageProduct $imageProduct)
    {
        $this->cateRepo = $cateRepo;
        $this->product = $product;
        $this->imageProduct = $imageProduct;
    }

    /**
     * Danh sách sản phẩm chưa được duyệt
     *
     * @return void
     */
    public function index()
    {
        $products = $this->product->where('status', Product::STATUS_DEFAULT)->latest()->get();
        return view('backend.products.index', compact('products'));
    }

    /**
     * Danh sách sản phẩm đã được duyệt
     *
     * @return void
     */
    public function listApproved()
    {
        $products = $this->product->WhereIn('status', [Product::STATUS_ACTIVE, Product::STATUS_HIDEN])->latest()->get();
        return view('backend.products.list-approved', compact('products'));
    }

    
    public function create()
    {
        $cates = $this->cateRepo->getAll();
        return view('backend.products.add', compact('cates'));
    }

    public function store(AddProductRequest $request)
    {
        $dataProduct = [
            'product_name'=> ucwords($request->name),
            'slug'=> Str::slug($request->name),
            'cate_id'=> $request->slCate,
            'price'=> $request->price,
            'promotion'=> $request->promotion,
            'description'=> $request->description,
            'admin_id'=> auth()->id()
        ];
        $dataUploadImage = $this->storageTraitUpload($request, 'image', 'products');
        if(!empty($dataUploadImage)) {
            $dataProduct['image'] = $dataUploadImage['file_name'];
        }

        $product = $this->product->create($dataProduct);

        //Insert data to image_details
        if($request->hasFile('image_detail')) {
            foreach($request->image_detail as $fileitem) {
                $dataProductImageDetail = $this->storageTraitUploadMultiple($fileitem, 'imagesdetail');
                $product->images()->create([
                    'image_detail' => $dataProductImageDetail['file_name']
                ]);
            }
        }
        return redirect()->route('products.index')->with('success', __('notification.add_success'));
    }

    /**
     * Hiển thị chi tiết sản phẩm
     *
     * @param [type] $id
     * @return void
     */
    public function show($id)
    {
        $product = $this->product->find($id);
        return view('backend.products.detail-product', compact('product'));
    }

    /**
     * Hiển thị form sửa sản phẩm
     *
     * @param [type] $id
     * @return void
     */
    public function edit($id)
    {
        $product = $this->product->find($id);
        $cates = $this->cateRepo->getAll();
        $imagesDetail = $this->imageProduct->where('product_id', $product->id)->get();
        return view('backend.products.edit', compact('product', 'cates', 'imagesDetail'));
    }

    /**
     * Xoá ảnh chi tiết sản phẩm
     *
     * @param [type] $id
     * @param [type] $id_image
     * @return void
     */
    public function getdeleteImageDetail($id, $id_image)
    {
        $image_detail = $this->imageProduct->where('product_id', $id)->where('id', $id_image)->first();
        $image_detail->delete();
        return response()->json([
            'message' => __('notification.delete_success')
        ], Response::HTTP_OK);
    }

    /**
     * Cập nhật sản phẩm
     *
     * @param Request $request
     * @param [type] $id
     * @return void
     */
    public function update(Request $request, $id)
    {
        $dataProduct = [
            'product_name'=> ucwords($request->name),
            'slug'=> Str::slug($request->name),
            'cate_id'=> $request->slCate,
            'price'=> $request->price,
            'promotion'=> $request->promotion,
            'description'=> $request->description,
            'admin_id'=> auth()->id()
        ];

        $dataUploadImage = $this->storageTraitUpload($request, 'image', 'products');
        if(!empty($dataUploadImage)) {
            $dataProduct['image'] = $dataUploadImage['file_name'];
        }
        $this->product->find($id)->update($dataProduct);
        $product = $this->product->find($id);

        //Insert data to image_details
        if($request->hasFile('image_detail')) {
            foreach($request->image_detail as $fileitem) {
                $dataProductImageDetail = $this->storageTraitUploadMultiple($fileitem, 'imagesdetail');
                $product->images()->create([
                    'image_detail' => $dataProductImageDetail['file_name']
                ]);
            }
        }
        return redirect()->back()->with('success', __('notification.update_success'));
    }

    /**
     * Xoá sản phẩm chưa duyệt
     * @param [type] $id
     * @return void
     */
    public function destroy($id)
    {
        $product = $this->product->find($id);

        if ($product) {
            if ($product->status == Product::STATUS_DEFAULT) {
                $product->delete();
                return response()->json([
                    'message' => __('notification.delete_success')
                ], Response::HTTP_OK);
            }            
        }

        return response()->json([
            'message' => __('notification.not_found')
        ], Response::HTTP_NOT_FOUND);
    }

    /**
     * Xoá sản phẩm trong danh sách đã duyệt
     *
     * @param [type] $id
     * @return void
     */
    public function getDeleteApproved($id)
    {
        if(auth()->guard('admin')->user()->level == Admin::MEMBER){
            return response()->json([
                'message' => __('notification.not_forbidden')
            ], Response::HTTP_FORBIDDEN);
        }
        $product = $this->product->find($id);

        if ($product) {
            $product->delete();
            return response()->json([
                'message' => __('notification.delete_success')
            ], Response::HTTP_OK);
        }

        return response()->json([
            'message' => __('notification.not_found')
        ], Response::HTTP_NOT_FOUND);
    }

    /**
     * Thay đổi trạng thái sản phẩm
     *
     * @param Request $request
     * @param [type] $id
     * @return void
     */
    public function changeStatus(Request $request, $id)
    {
        $this->product->find($id)->update(['status' => $request->status]);
        return response()->json([
            'message' => __('notification.change_success')
        ], Response::HTTP_OK);
    }

    /**
     * Duyệt sản phẩm
     *
     * @param [type] $id
     * @return void
     */
    public function getbrowseProduct($id)
    {
        if(auth()->guard('admin')->user()->level == Admin::MEMBER){
            return response()->json([
                'message' => __('notification.not_forbidden')
            ], Response::HTTP_FORBIDDEN);
        }
        $product = $this->product->find($id);

        if ($product) {
            $product->update(['status' => Product::STATUS_ACTIVE]);
            return response()->json([
                'message' => __('notification.approved_success')
            ], Response::HTTP_OK);
        }

        return response()->json([
            'message' => __('notification.not_found')
        ], Response::HTTP_NOT_FOUND);
    }
}

resources/views/backend/products/detail-product.blade.php
@extends('backend.master')
@section('title', 'Chi tiết sản phẩm' . ' ' . $product->product_name)
@section('content')
    <div class="row m-t-30">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-body display_data">
                    <div class="position-relative row form-group">
                        <label for="" class="col-md-3 text-md-right col-form-label">Ảnh đại diện</label>
                        <div class="col-md-9 col-xl-8">
                            <ul class="text-nowrap overflow-auto" id="images">
                                <li class="d-inline-block mr-1" style="position: relative;">
                                    <img style="height: 150px;" src="{{ $product->image_url }}" alt="Image">
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="position-relative row form-group">
                        <label for="" class="col-md-3 text-md-right col-form-label">Ảnh chi tiết sản
                            phẩm</label>
                        <div class="col-md-9 col-xl-8">
                            <ul class="text-nowrap overflow-auto" id="images">
                                @foreach ($product->images as $productImage)
                                    <li class="d-inline-block mr-1" style="position: relative;">
                                        <img style="height: 150px;"
                                            src="{{ asset('uploads/imagesdetail/' . $productImage->image_detail) }}"
                                            alt="Image">
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>

                    <div class="position-relative row form-group">
                        <label for="name" class="col-md-3 text-md-right col-form-label">Sản phẩm</label>
                        <div class="col-md-9 col-xl-8">
                            <p>{{ $product->product_name }}</p>
                        </div>
                    </div>

                    <div class="position-relative row form-group">
                        <label for="product_category_id" class="col-md-3 text-md-right col-form-label">Danh mục</label>
                        <div class="col-md-9 col-xl-8">
                            <p>{{ $product->category->name }}</p>
                        </div>
                    </div>

                    <div class="position-relative row form-group">
                        <label for="name" class="col-md-3 text-md-right col-form-label">Người đăng</label>
                        <div class="col-md-9 col-xl-8">
                            <p>{{ $product->admin->name }}</p>
                        </div>
                    </div>

                    {{-- <div class="position-relative row form-group">
                        <label for="content" class="col-md-3 text-md-right col-form-label">Content</label>
                        <div class="col-md-9 col-xl-8">
                            <p>High quality fabric, modern and youthful design</p>
                        </div>
                    </div> --}}

                    <div class="position-relative row form-group">
                        <label for="price" class="col-md-3 text-md-right col-form-label">Giá</label>
                        <div class="col-md-9 col-xl-8">
                            <p>{{ $product->format_price }} VNĐ</p>
                        </div>
                    </div>

                    <div class="position-relative row form-group">
                        <label for="discount" class="col-md-3 text-md-right col-form-label">Giá khuyến mãi</label>
                        <div class="col-md-9 col-xl-8">
                            <p>{{ $product->format_promotion }} VNĐ</p>
                        </div>
                    </div>

                    <div class="position-relative row form-group">
                        <label for="qty" class="col-md-3 text-md-right col-form-label">Số lượng</label>
                        <div class="col-md-9 col-xl-8">
                            <p>{{ $product->qty }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/products/list-approved.blade.php
@extends('backend.master')
@section('title', 'Danh sách sản phẩm')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <h3 class="title-5 m-b-35"></h3>
            <div class="table-data__tool">
                <div class="table-data__tool-right">
                    <a href="{{ route('products.create') }}"><button class="au-btn au-btn-icon btn-info au-btn--small">
                            <i class="zmdi zmdi-plus"></i>Thêm mới</button></a>

                    {{-- <div class="rs-select2--dark rs-select2--sm rs-select2--dark2">
                    <select class="js-select2" name="type">
                        <option selected="selected">Xuất file</option>
                        <option value="">Excel</option>
                        <option value="">PDF</option>
                    </select>
                    <div class="dropDownSelect2"></div>
                </div> --}}
                </div>
            </div>
            <div class="table-responsive table-responsive-data2">
                <table class="table table-data2 custom-table-data2">
                    <thead>
                        <tr>
                            <th>
                                <label class="au-checkbox">
                                    <input type="checkbox">
                                    <span class="au-checkmark"></span>
                                </label>
                            </th>
                            <th>STT</th>
                            <th>Sản phẩm</th>
                            <th>Giá (VND)</th>
                            <th>Khuyến mãi (%)</th>
                            <th>Trạng thái</th>
                            <th></th>
                            <th style="text-align: center;">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if ($products->count() != 0)
                            @foreach ($products as $key => $product)
                                <tr class="tr-shadow">
                                    <td>
                                        <label class="au-checkbox panel">
                                            <input type="checkbox">
                                            <span class="au-checkmark checkbox_childrent"></span>
                                        </label>
                                    </td>
                                    <td>{{ $key + 1 }}</td>
                                    <td>{{ $product->product_name }}</td>
                                    <td class="desc">{{ $product->format_price }}</td>
                                    <td class="desc">{{ $product->promotion }}</td>
                                    <td id="txtstatus{{ $product->id }}">
                                        @if ($product->status == 1)
                                            <span class="status--process">Kích hoạt</span>
                                        @elseif($product->status == 0)
                                            <span class="status--denied">Không kích hoạt</span>
                                        @endif
                                    </td>
                                    <td>
                                        <label class="switch switch-text switch-success" style="top: 4px;">
                                            <input type="checkbox" class="switch-input change-status"
                                                @if ($product->status == 1) ? checked="true" : checked="false" @endif
                                                data-id="{{ $product->id }}"
                                                data-url="{{ route('products.change.status', ['id' => $product->id]) }}">
                                            <span data-on="On" data-off="Off" class="switch-label unactive"></span>
                                            <span class="switch-handle"></span>
                                        </label>
                                    </td>
                                    <td>
                                        <div class="table-data-feature">
                                            
                                            <a href="{{ route('products.show', ['id' => $product->id]) }}"
                                                target="_blank"
                                                class="btn btn-hover-shine btn-outline-info border-0 btn-sm">
                                                Details
                                            </a>
                                            <a href="{{ route('products.edit', ['id' => $product->id]) }}" data-toggle="tooltip"
                                                title="Chỉnh sửa" data-placement="bottom"
                                                class="btn btn-outline-warning border-0 btn-sm">
                                                <span class="btn-icon-wrapper opacity-8">
                                                    <i class="fa fa-edit fa-w-20"></i>
                                                </span>
                                            </a>
                                            <a href="{{ route('variants.index', ['product_id' => $product->id]) }}" data-toggle="tooltip"
                                                title="Thêm thuộc tính" data-placement="bottom"
                                                class="btn btn-outline-success border-0 btn-sm">
                                                <span class="btn-icon-wrapper opacity-8">
                                                    <i class="fa fa-plus fa-w-20"></i>
                                                </span>
                                            </a>
                                            <a href="" class="deleteItem" data-url="{{ route('products.getDeleteApproved', ['id' => $product->id]) }}">
                                                <button class="btn btn-hover-shine btn-outline-danger border-0 btn-sm btn-delete" data-toggle="tooltip" title="Xoá"
                                                data-placement="bottom">
                                                    <span class="btn-icon-wrapper opacity-8"><i class="fa fa-trash fa-w-20"></i></span>
                                                </button>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr class="tr-shadow">
                                <td colspan="8">Không có sản phẩm nào được duyệt.</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection